version: '3.1'
services:
  app:
    image: 'alexssilva/customer-app:latest'
    ports:
      - "8080:8080"
    build:
      context: .
    container_name: app
    depends_on:
      - PostgreSQL
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/builders_customer
      - SPRING_DATASOURCE_USERNAME=builders
      - SPRING_DATASOURCE_PASSWORD=builders
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  PostgreSQL:
    image: 'postgres:14.0-alpine'
    container_name: postgredb
    environment:
      - POSTGRES_USER=builders
      - POSTGRES_PASSWORD=builders
