version: '3'
services:
 docker-app:
    image: alexssilva/customer:0.0.1
    ports:
      - "8080:8080"
    depends_on:
      - docker-postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://docker-postgres:5432/builders_customer
      - SPRING_DATASOURCE_USERNAME=builders
      - SPRING_DATASOURCE_PASSWORD=builders
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update  
 docker-postgres:
    image: postgres:14.0-alpine
    environment:
      - POSTGRES_DB=builders_customer
      - POSTGRES_USER=builders
      - POSTGRES_PASSWORD=builders
