version: '3.1'
services:
  API:
    image: alexssilva/customer-app
    ports:
      - "8080:8080"
    depends_on:
      PostgreSQL:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://PostgreSQL:5432/builders_customer
      - SPRING_DATASOURCE_USERNAME=builders
      - SPRING_DATASOURCE_PASSWORD=builders
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  PostgreSQL:
    image: postgres:14.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=builders
      - POSTGRES_USER=builders
      - POSTGRES_DB=builders_customer
